scripts/build.ps1

fix: fix version

---

scripts/build.ps1

fix: fix chocolateyinstall

---

.github/workflows/main.yaml
scripts/build.ps1
scripts/templates/chocolateyinstall.ps1
scripts/templates/kaytu.nuspec

fix: fix windows zip checksum

---

.github/workflows/main.yaml
scripts/build.ps1
scripts/templates/chocolateyinstall.ps1

fix: kaytu version in chocolatey

---

scripts/templates/kaytu.nuspec

fix: update description

---

.github/workflows/main.yaml

fix: update workflow needs

---

.github/workflows/main.yaml
scripts/build.ps1

fix: remove push chocolatey

---

.github/workflows/main.yaml

fix: publish to chocolatey input

---

cmd/optimize/view/ec2_instance_detail.go
pkg/api/wastage/ec2_instance.go
scripts/build.ps1

fix: add license price to client details view

---

cmd/optimize/view/ec2_instance_detail.go
cmd/optimize/view/ec2_instance_optimizations.go
go.mod
go.sum

Implementing new table component to show changes with proper styling:

feat: Adds new table component to show changes with proper styling

---

cmd/optimize/view/app.go
cmd/optimize/view/ec2_instance_optimizations.go
go.mod
go.sum

- **fix: show skipped instances**
- **fix: only show reason if it exists**

fix show skipped

---

.github/workflows/dev.yaml

fix: Fixes cosign

---

pkg/utils/view.go

fix: byte unit conversions

---

view/preferences_configuration.go
view/preferences_item.go
view/view_optimization_details.go

fix: Remove EC2 Instance from placeholder

---

pkg/plugin/manager.go

fix: Randomizing port

---

pkg/plugin/plugin.go
pkg/server/config.go
pkg/server/plugin.go

fix: windows paths

---

pkg/plugin/manager.go
pkg/server/config.go

fix: add .exe to windows executeable

---

cmd/root.go
pkg/plugin/manager.go
view/non_interactive_view.go

fix: non-interactive mode finished

---

go.mod
go.sum
view/non_interactive_view.go

fix: add csv export

---

.github/workflows/main.yaml

fix: fix windows release zip file checksum

---

approved_plugins
cmd/plugin/cmd.go
cmd/plugin/install.go
cmd/plugin/uninstall.go
cmd/root.go
pkg/plugin/manager.go

Fix approved plugins

---

pkg/plugin/manager.go

fix: add print to unistall states

---

pkg/api/auth0/device_code.go

fix: open login link in default browser

---

view/page_optimization.go
view/page_optimization_details.go

fix: add resource name to details

---

pkg/utils/view.go

fix: fix FormatFloat function

---

view/app.go

fix: fix small widnow size responsive issue

---

view/page_preferences.go

Fix chartoptimizationitem preferences

---

view/non_interactive_view.go

fix: fix csv output

---

pkg/plugin/manager.go
pkg/version/version.go
view/non_interactive_view.go

Fix custom noninteractive

---

pkg/plugin/sdk/processor.go
pkg/plugin/sdk/sdk.go

- **fix: sdk context**
- **fix: sdk context**

fix sdk context

---

cmd/root.go
cmd/singal.go
main.go
pkg/plugin/sdk/job_queue.go
pkg/plugin/sdk/sdk.go
pkg/plugin/sdk/stream.go

- **fix: delete test**
- **fix: add signal handling**
- **fix: add signal handling**
- **fix: add signal handling**

fix update sdk

---

cmd/plugin/install.go
cmd/plugin/uninstall.go
cmd/root.go
pkg/api/auth0/device_code.go
pkg/server/update.go

fix: change login prints to stderr outputs

---

cmd/plugin/uninstall.go

fix: fix stderr output

---

cmd/root.go
go.mod
go.sum
view/page_resource_details_plugin_custom.go

- **feat: add auto install**
- **fix: security vulnerability**

feat add auto install

---

cmd/root.go
pkg/plugin/manager.go
view/root_command_view.go

fix: add print summary to root commands

---

cmd/root.go

fix: fix kaytu plugin root commands name
